/**
 * Generates supabase/seed/seed.sql from @adhyapak/core.
 *
 * Imports the core source by path rather than by package name: the package ships
 * TypeScript with no build step, and tsx resolves the .ts entry directly.
 *
 * The researched content lives in TypeScript, where it is typechecked and
 * reviewable in a diff. This turns it into SQL so the same content lands in
 * Postgres. Run it after editing anything under packages/core/src/data:
 *
 *   npm run seed:generate --workspace=@adhyapak/backend
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  BATCHES,
  CURRENT_AFFAIRS,
  DOUBTS,
  EDUCATORS,
  EXAMS,
  NOTES,
  QUESTIONS,
  SUBJECTS,
  TESTS,
  VIDEOS,
} from '../../packages/core/src/index.ts';

/** Postgres string literal. */
const s = (value: string | null | undefined): string =>
  value === null || value === undefined ? 'null' : `'${value.replace(/'/g, "''")}'`;

/** Postgres jsonb literal. */
const j = (value: unknown): string => `${s(JSON.stringify(value))}::jsonb`;

/** Postgres text[] literal. */
const arr = (values: string[]): string =>
  values.length ? `array[${values.map(s).join(', ')}]::text[]` : `'{}'::text[]`;

const n = (value: number | null | undefined): string =>
  value === null || value === undefined ? 'null' : String(value);

const b = (value: boolean | undefined): string => (value ? 'true' : 'false');

const rows = (table: string, columns: string[], values: string[][]): string => {
  if (!values.length) return '';
  return (
    `insert into ${table} (${columns.join(', ')}) values\n` +
    values.map((r) => `  (${r.join(', ')})`).join(',\n') +
    `\non conflict (${columns[0]}) do nothing;\n`
  );
};

const out: string[] = [
  '-- Generated by supabase/seed/generate-seed.ts — do not edit by hand.',
  '-- Regenerate with: npm run seed:generate --workspace=@adhyapak/backend',
  '',
  'begin;',
  '',
];

/* --------------------------------------------------------------- taxonomy */

out.push(
  rows(
    'subjects',
    ['id', 'name', 'icon', 'color', 'description', 'sort_order'],
    SUBJECTS.map((x, i) => [s(x.id), j(x.name), s(x.icon), s(x.color), j(x.description), n(i)]),
  ),
);

out.push(
  rows(
    'topics',
    ['id', 'subject_id', 'name', 'weightage', 'question_count'],
    SUBJECTS.flatMap((subject) =>
      subject.topics.map((t) => [
        s(t.id),
        s(t.subjectId),
        j(t.name),
        n(t.weightage),
        n(t.questionCount),
      ]),
    ),
  ),
);

/* ------------------------------------------------------------------ exams */

out.push(
  rows(
    'exams',
    [
      'id', 'slug', 'name', 'short_name', 'authority', 'scope', 'state', 'about',
      'frequency', 'color', 'emoji', 'learners', 'next_exam_date', 'eligibility',
      'highlights', 'official_site', 'vacancies',
    ],
    EXAMS.map((e) => [
      s(e.id), s(e.slug), j(e.name), s(e.shortName), j(e.authority), s(e.scope),
      e.state ? j(e.state) : 'null', j(e.about), j(e.frequency), s(e.color), s(e.emoji),
      n(e.learners), e.nextExamDate ? `${s(e.nextExamDate)}::date` : 'null',
      j(e.eligibility), j(e.highlights), s(e.officialSite), n(e.vacancies),
    ]),
  ),
);

// exam_updates and exam_sources use generated uuids, so they are cleared first
// rather than relying on a conflict target.
out.push('delete from exam_updates;');
out.push(
  'insert into exam_updates (exam_id, date, kind, title, detail) values\n' +
    EXAMS.flatMap((e) =>
      e.updates.map(
        (u) => `  (${s(e.id)}, ${s(u.date)}::date, ${s(u.kind)}, ${j(u.title)}, ${j(u.detail)})`,
      ),
    ).join(',\n') +
    ';\n',
);

out.push('delete from exam_sources;');
out.push(
  'insert into exam_sources (exam_id, label, url, checked_on) values\n' +
    EXAMS.flatMap((e) =>
      e.sources.map(
        (src) => `  (${s(e.id)}, ${s(src.label)}, ${s(src.url)}, ${s(src.checkedOn)}::date)`,
      ),
    ).join(',\n') +
    ';\n',
);

out.push(
  rows(
    'exam_papers',
    [
      'id', 'exam_id', 'name', 'level', 'marks_per_question', 'negative_marking',
      'duration_minutes', 'total_questions', 'cutoff_general', 'cutoff_reserved', 'sort_order',
    ],
    EXAMS.flatMap((e) =>
      e.papers.map((p, i) => [
        s(p.id), s(e.id), j(p.name), s(p.level), n(p.marksPerQuestion), n(p.negativeMarking),
        n(p.durationMinutes), n(p.totalQuestions), n(p.cutoffGeneral), n(p.cutoffReserved), n(i),
      ]),
    ),
  ),
);

out.push('delete from paper_sections;');
out.push(
  'insert into paper_sections (paper_id, subject_id, questions, marks, sort_order) values\n' +
    EXAMS.flatMap((e) =>
      e.papers.flatMap((p) =>
        p.sections.map(
          (sec, i) => `  (${s(p.id)}, ${s(sec.subjectId)}, ${n(sec.questions)}, ${n(sec.marks)}, ${n(i)})`,
        ),
      ),
    ).join(',\n') +
    ';\n',
);

/* -------------------------------------------------------------- educators */

out.push(
  rows(
    'educators',
    ['id', 'name', 'avatar', 'headline', 'bio', 'subjects', 'experience_years', 'rating', 'learners', 'languages'],
    EDUCATORS.map((e) => [
      s(e.id), s(e.name), s(e.avatar), j(e.headline), j(e.bio), arr(e.subjects),
      n(e.experienceYears), n(e.rating), n(e.learners), arr(e.languages),
    ]),
  ),
);

/* -------------------------------------------------------------- questions */

out.push(
  rows(
    'questions',
    [
      'id', 'subject_id', 'topic_id', 'exam_ids', 'text', 'options', 'correct_index',
      'explanation', 'difficulty', 'previous_year', 'avg_time_seconds', 'accuracy',
    ],
    QUESTIONS.map((q) => [
      s(q.id), s(q.subjectId), s(q.topicId), arr(q.examIds), j(q.text), j(q.options),
      n(q.correctIndex), j(q.explanation), s(q.difficulty), s(q.previousYear),
      n(q.avgTimeSeconds), n(q.accuracy),
    ]),
  ),
);

/* ------------------------------------------------------------------ notes */

out.push(
  rows(
    'notes',
    ['id', 'title', 'subject_id', 'topic_id', 'exam_ids', 'educator_id', 'pages', 'downloads', 'access', 'language', 'tags', 'updated_at'],
    NOTES.map((x) => [
      s(x.id), j(x.title), s(x.subjectId), s(x.topicId ?? null), arr(x.examIds),
      s(x.educatorId), n(x.pages), n(x.downloads), s(x.access), s(x.language), j(x.tags),
      `${s(x.updatedAt)}::timestamptz`,
    ]),
  ),
);

out.push('delete from note_sections;');
out.push(
  'insert into note_sections (note_id, heading, body, callout, bullets, sort_order) values\n' +
    NOTES.flatMap((note) =>
      note.sections.map(
        (sec, i) =>
          `  (${s(note.id)}, ${j(sec.heading)}, ${j(sec.body)}, ${sec.callout ? j(sec.callout) : 'null'}, ${j(sec.bullets ?? [])}, ${n(i)})`,
      ),
    ).join(',\n') +
    ';\n',
);

/* ----------------------------------------------------------------- videos */

out.push(
  rows(
    'videos',
    [
      'id', 'title', 'description', 'educator_id', 'subject_id', 'topic_id', 'exam_ids',
      'external_url', 'thumbnail', 'duration_seconds', 'views', 'published_at', 'access',
      'language', 'is_live', 'live_starts_at',
    ],
    VIDEOS.map((v) => [
      s(v.id), j(v.title), j(v.description), s(v.educatorId), s(v.subjectId),
      s(v.topicId ?? null), arr(v.examIds), s(v.src), s(v.thumbnail), n(v.durationSeconds),
      n(v.views), `${s(v.publishedAt)}::date`, s(v.access), s(v.language), b(v.isLive),
      v.liveStartsAt ? `${s(v.liveStartsAt)}::timestamptz` : 'null',
    ]),
  ),
);

out.push('delete from video_chapters;');
const chapterRows = VIDEOS.flatMap((v) =>
  v.chapters.map((c) => `  (${s(v.id)}, ${n(c.at)}, ${j(c.title)})`),
);
if (chapterRows.length) {
  out.push(
    'insert into video_chapters (video_id, at_seconds, title) values\n' +
      chapterRows.join(',\n') +
      ';\n',
  );
}

/* ---------------------------------------------------------------- batches */

out.push(
  rows(
    'batches',
    ['id', 'title', 'exam_id', 'paper_id', 'educator_ids', 'starts_at', 'ends_at', 'schedule', 'language', 'enrolled', 'access', 'color', 'includes'],
    BATCHES.map((x) => [
      s(x.id), j(x.title), s(x.examId), s(x.paperId ?? null), arr(x.educatorIds),
      `${s(x.startsAt)}::date`, `${s(x.endsAt)}::date`, j(x.schedule), s(x.language),
      n(x.enrolled), s(x.access), s(x.color), j(x.includes),
    ]),
  ),
);

out.push(
  rows(
    'batch_modules',
    ['id', 'batch_id', 'title', 'subject_id', 'video_ids', 'note_ids', 'question_ids', 'sort_order'],
    BATCHES.flatMap((batch) =>
      batch.syllabus.map((m, i) => [
        s(m.id), s(batch.id), j(m.title), s(m.subjectId), arr(m.videoIds), arr(m.noteIds),
        arr(m.questionIds), n(i),
      ]),
    ),
  ),
);

/* ------------------------------------------------------------------ tests */

out.push(
  rows(
    'tests',
    ['id', 'title', 'exam_id', 'paper_id', 'type', 'duration_minutes', 'marks_per_question', 'negative_marking', 'access', 'attempts', 'year', 'instructions'],
    TESTS.map((t) => [
      s(t.id), j(t.title), s(t.examId), s(t.paperId ?? null), s(t.type), n(t.durationMinutes),
      n(t.marksPerQuestion), n(t.negativeMarking), s(t.access), n(t.attempts), n(t.year),
      j(t.instructions),
    ]),
  ),
);

out.push(
  rows(
    'test_sections',
    ['id', 'test_id', 'name', 'subject_id', 'question_ids', 'sort_order'],
    TESTS.flatMap((test) =>
      test.sections.map((sec, i) => [
        s(`${test.id}--${sec.id}`), s(test.id), j(sec.name), s(sec.subjectId),
        arr(sec.questionIds), n(i),
      ]),
    ),
  ),
);

/* ------------------------------------------------------------------ feeds */

out.push(
  rows(
    'current_affairs',
    ['id', 'title', 'summary', 'date', 'tags', 'exam_ids'],
    CURRENT_AFFAIRS.map((c) => [
      s(c.id), j(c.title), j(c.summary), `${s(c.date)}::date`, j(c.tags), arr(c.examIds),
    ]),
  ),
);

out.push('delete from doubt_answers;');
out.push('delete from doubts;');
for (const d of DOUBTS) {
  out.push(
    `insert into doubts (id, asked_by, avatar, subject_id, question, asked_at, upvotes)\n` +
      `values (gen_random_uuid(), ${s(d.askedBy)}, ${s(d.avatar)}, ${s(d.subjectId)}, ${j(d.question)}, ${s(d.askedAt)}::timestamptz, ${n(d.upvotes)});`,
  );
  for (const a of d.answers) {
    out.push(
      `insert into doubt_answers (doubt_id, by_name, is_educator, body, answered_at, upvotes)\n` +
        `select id, ${s(a.by)}, ${b(a.isEducator)}, ${j(a.body)}, ${s(a.answeredAt)}::timestamptz, ${n(a.upvotes)}\n` +
        `from doubts where question = ${j(d.question)} limit 1;`,
    );
  }
}

out.push('', 'commit;', '');

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, 'seed.sql');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out.filter(Boolean).join('\n'));

console.log(
  `Wrote ${target}\n` +
    `  ${SUBJECTS.length} subjects, ${EXAMS.length} exams, ${QUESTIONS.length} questions,\n` +
    `  ${NOTES.length} notes, ${VIDEOS.length} videos, ${BATCHES.length} batches, ${TESTS.length} tests`,
);
