/**
 * Bulk question importer.
 *
 *   npx tsx seed/import-questions.ts bank.csv --exam htet --dry-run
 *   npx tsx seed/import-questions.ts bank.csv --exam htet > import.sql
 *
 * Reads a CSV, validates every row against the live reference ids, and prints
 * the SQL to insert the rows that passed. It never connects to a database:
 * the output is inspectable, reviewable and replayable, and a run that goes
 * wrong costs nothing because nothing was written.
 *
 * Rejected rows are reported on stderr with their spreadsheet line number, so
 * the file can be corrected and re-run.
 *
 * Imported questions arrive as drafts. Publishing is a separate, deliberate act
 * — `select set_question_status(id, 'published')` — so nothing reaches a learner
 * because a spreadsheet said so.
 */
import { readFileSync } from 'node:fs';
import {
  EXAMS,
  SUBJECTS,
  describeReport,
  importQuestionsFromCsv,
  refsFrom,
  type ContentQuestion,
  type ImportOptions,
} from '../../packages/core/src/index.ts';

const args = process.argv.slice(2);
const file = args.find((a) => !a.startsWith('--'));
const flag = (name: string): string | undefined => {
  const hit = args.find((a) => a === `--${name}` || a.startsWith(`--${name}=`));
  if (!hit) return undefined;
  return hit.includes('=') ? hit.split('=').slice(1).join('=') : '';
};

if (!file) {
  console.error('usage: tsx seed/import-questions.ts <file.csv> [--exam id] [--publish] [--dry-run]');
  process.exit(1);
}

const refs = refsFrom({
  exams: EXAMS.map((e) => e.id),
  subjects: SUBJECTS.map((s) => s.id),
  topics: SUBJECTS.flatMap((s) => s.topics.map((t) => t.id)),
});

const options: ImportOptions = {
  refs,
  defaultExamIds: flag('exam') ? [flag('exam')!] : [],
  // Imports are drafts unless explicitly told otherwise, and even then the flag
  // has to be typed by a human who is watching.
  status: flag('publish') !== undefined ? 'published' : 'draft',
  idPrefix: flag('prefix') || 'q-import',
};

const report = importQuestionsFromCsv(readFileSync(file, 'utf8'), options);

console.error(describeReport(report));

if (flag('dry-run') !== undefined) {
  console.error('\nDry run — no SQL written.');
  process.exit(report.rejected.length ? 1 : 0);
}

const q = (v: string | null | undefined): string =>
  v === null || v === undefined ? 'null' : `'${v.replace(/'/g, "''")}'`;
const json = (v: unknown): string => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const arr = (v: string[]): string =>
  v.length ? `array[${v.map((s) => q(s)).join(',')}]::text[]` : `'{}'::text[]`;
const num = (v: number | undefined): string => (v === undefined ? 'null' : String(v));

const values = (row: ContentQuestion): string =>
  [
    q(row.id),
    q(row.status),
    q(row.kind),
    q(row.subjectId),
    q(row.topicId),
    row.unitId ? q(row.unitId) : 'null',
    row.subtopicId ? q(row.subtopicId) : 'null',
    arr(row.examIds),
    arr(row.levels),
    json(row.text),
    json(row.options),
    String(row.correctIndices[0] ?? 0),
    `array[${row.correctIndices.join(',')}]::int[]`,
    json(row.explanation),
    q(row.difficulty),
    num(row.marks),
    num(row.negativeMarks),
    row.pyq ? q(row.pyq.examId) : 'null',
    num(row.pyq?.year),
    row.pyq?.session ? q(row.pyq.session) : 'null',
    row.pyq?.paperLabel ? q(row.pyq.paperLabel) : 'null',
    row.pyq?.shift ? q(row.pyq.shift) : 'null',
    num(row.pyq?.questionNumber),
    row.source ? q(row.source) : 'null',
    arr(row.tags),
    arr(row.conceptTags),
    row.syllabusRef ? q(row.syllabusRef) : 'null',
    String(row.avgTimeSeconds),
    String(row.accuracy),
  ].join(', ');

const lines: string[] = [
  `-- Generated by seed/import-questions.ts from ${file}`,
  `-- ${report.stats.accepted} questions, ${report.stats.withPyq} with previous-year metadata.`,
  '-- Imported as drafts: publish with set_question_status(id, \'published\').',
  'begin;',
];

for (const row of report.accepted) {
  lines.push(
    `insert into questions (
  id, status, kind, subject_id, topic_id, unit_id, subtopic_id, exam_ids, levels,
  text, options, correct_index, correct_indices, explanation, difficulty,
  marks, negative_marks,
  pyq_exam_id, pyq_year, pyq_session, pyq_paper_label, pyq_shift, pyq_question_number,
  source, tags, concept_tags, syllabus_ref, avg_time_seconds, accuracy
) values (${values(row)})
on conflict (id) do update set
  text = excluded.text, options = excluded.options,
  correct_index = excluded.correct_index, correct_indices = excluded.correct_indices,
  explanation = excluded.explanation, updated_at = now();`,
  );
}

lines.push('commit;');
console.log(lines.join('\n'));
